spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/spark_scene_htmx
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    view:
      prefix: /templates/
      suffix: .html
management:
  endpoints:
    web:
      exposure:
        include: mappings
server:
  port: 8088